image:
  repo: quay.io/coreos/flannel
  tag: v0.7.0-amd64
  pullPolicy: IfNotPresent

subnet: 10.244.0.0/16

serviceAccount:
  enabled: true
  name: flannel

rbac:
  enabled: true

args:
  "ip-masq": true
  "kube-subnet-mgr": true

nodeSelector:
  beta.kubernetes.io/arch: amd64

tolerations:
  defaults: true
  #extra: []
