apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: True
      containers:
      - name: main
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        command:
        - pixiecore
        - api
        - --dhcp-no-bind
        - --port
        - "9200"
        - {{ .Values.service | quote }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 67
          name: dns-udp
          protocol: UDP
