apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kpnbaseoses.kubeprovision.github.com
spec:
  group: kubeprovision.github.com
  version: v1
  scope: Namespaced
  names:
    plural: kpnbaseoses
    # singular name to be used as an alias on the CLI and for display
    singular: kpnbaseos
    kind: BaseOS
