apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.httpPort | int }}
    targetPort: http
    name: http
  selector:
    app: {{ template "fullname" . }}
{{- if .Values.externalIPs }}
  externalIPs:
{{ toYaml .Values.externalIPs | indent 4 }}
{{- end }}
