apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      hostNetwork: true
      containers:
      - name: main
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command:
        - /bin/bash
        - -c
        - |
          dhcpd -d -user daemon -group daemon {{ join " " .Values.interfaces }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
#FIXME this and pixiecore block each other....
#       ports:
#       - containerPort: 67
#         name: dhcp
#         protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /etc/dhcp
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}

