apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
spec:
  selector:
    app: {{ template "fullname" . }}
  ports:
  - name: dhcp
    port: {{ .Values.dhcpPort }}
    protocol: UDP
  type: {{ .Values.serviceType }}
  externalIPs:
  - {{ .Values.externalIP }}
