image: kfox1111/dhcp
imageTag: 4.2.5-58.el7.centos-2
imagePullPolicy: IfNotPresent
serviceType: ClusterIP
resources: {}
interfaces: []

config:
    manage: true

    defaultLeaseTime: 600
    maxLeaseTime: 7200
    ddnsUpdateStyle: none

    subnets:
      - start: 172.22.0.0
        netmask: 255.255.255.0
#FIXME rangeStart/End should not be used until pv support is added.
#        rangeStart: 192.168.0.100
#        rangeEnd: 192.168.0.254
    #NOTE this is temporary until kube-dhcp is done. This info should be in k8s itself.
    groups:
    - domainName: example.com
      domainNameServers: [172.22.0.1]
      routers: [172.22.0.1]
      subnetMask: 255.255.255.0
      hosts:
      - name: c1
        mac: 00:01:02:aa:bb:cc
        ip: 172.22.0.2
