dependencies:
  - name: ceph-secret
    repository: file://../ceph-secret
    alias: userSecret
    version: 1.0.0
    condition: userSecret.manage
  - name: ceph-secret
    repository: file://../ceph-secret
    alias: adminSecret
    version: 1.0.0
    condition: adminSecret.manage
