{{- $global := . }}
{{- range (list "frontend" "backend") }}
{{- $section := (index $global.Values .) }}
{{- if $section.ingress.enabled }}
---
{{- $fullNameKey := printf "generic-three-tier.%s.fullname" . }}
{{- $fullName := include $fullNameKey $global }}
{{- $ingressPath := $section.ingress.path }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "generic-three-tier.name" $global }}
    chart: {{ template "generic-three-tier.chart" $global }}
    release: {{ $global.Release.Name }}
    component: {{ . }}
    heritage: {{ $global.Release.Service }}
{{- with $section.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if $section.ingress.tls }}
  tls:
  {{- range $section.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $section.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
{{- end }}
{{- end }}
